# Import the random module and set up a winner variable
import random

winner = ""

# A number between 0 - 2 is generated by the computer and it's mapped to rock, paper or scissors
random_choice = random.randint(0,2)

if random_choice == 0:
    computer_choice = "rock"
elif random_choice == 1:
    computer_choice = "paper"
else:
    computer_choice = "scissors"

# while the user choice isn't valid it is asked to input it again
user_choice = ""
while (user_choice != "rock" and user_choice != "paper" and user_choice != "scissors"):
    user_choice = input("rock, paper or scissors? ")

# Rock, paper, scissors rules
if computer_choice == user_choice:
    winner = "Tie"
elif computer_choice == "paper" and user_choice == "rock":
    winner = "Computer"
elif computer_choice == "scissors" and user_choice == "paper":
    winner = "Computer"
elif computer_choice == "rock" and user_choice == "scissors":
    winner = "Computer"
else:
    winner = "User"

# The winner is reveled
if winner == "Tie":
    print("We both chose", computer_choice + ", play again.")
else:
    print(winner, "won. The computer chose", computer_choice + ".")
